# .github/workflows/monkeytype-reminder.yml
name: MonkeyType Streak Guardian

on:
  schedule:
    # Morning motivation (7 AM UTC)
    - cron: '0 7 * * 1-7'
    # Midday check (12 PM UTC)
    - cron: '0 12 * * 1-7'
    # Afternoon reminder (4 PM UTC)
    - cron: '0 16 * * 1-7'
    # Evening warning (9 PM UTC)
    - cron: '0 21 * * 1-7'
    # Late night final warning (11 PM UTC)
    - cron: '0 23 * * 1-7'
    # Weekly stats summary (Sunday 10 AM UTC)
    - cron: '0 10 * * 0'
  workflow_dispatch: # Manual testing
    inputs:
      test_mode:
        description: 'Test specific reminder type'
        required: false
        default: 'current'
        type: choice
        options:
        - current
        - morning
        - afternoon
        - evening
        - warning
        - weekly

jobs:
  streak-guardian:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run MonkeyType Streak Guardian
      env:
        MONKEYTYPE_APE_KEY: ${{ secrets.MONKEYTYPE_APE_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TEST_MODE: ${{ github.event.inputs.test_mode }}
      run: node streak-guardian.js
    
    - name: Update streak history
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "📊 Update streak history - $(date)"
        git push || echo "No changes to push"
