name: Send Daily Reminders

on:
  schedule:
    # Run every hour to check for reminders
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install python-telegram-bot aiohttp
        
    - name: Download user data
      run: |
        # Download users.json from repository if it exists
        if [ -f users.json ]; then
          echo "users.json found"
        else
          echo "{}" > users.json
        fi
        
    - name: Send reminders
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        REMINDER_MODE: 'true'
      run: |
        python main.py
        
    - name: Commit and push updated user data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add users.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update user reminder data [skip ci]"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
