name: Test Reminders

on:
  workflow_dispatch: # Manual trigger only

permissions:
  contents: write
  actions: read

jobs:
  test-reminders:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install python-telegram-bot aiohttp
        
    - name: Download user data
      run: |
        if [ -f users.json ]; then
          echo "users.json found"
          cat users.json
        else
          echo "{}" > users.json
          echo "Created empty users.json"
        fi
        
    - name: Test send reminders (FORCE MODE)
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        REMINDER_MODE: 'true'
        TEST_MODE: 'true'
      run: |
        echo "Running in TEST MODE - will send reminders regardless of time"
        python main.py
